runtime: nodejs14   # specify the Node.js runtime

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15

instance_class: F2

network:
  session_affinity: true

entrypoint: npm run start  # the command to start your application

env_variables:
  PUBLIC_URL: "http://norvish-restful.appspot.com"

handlers:
  - url: /(.*\.(json|ico|js))$
    static_files: dist/\1
    upload: dist/.*\.(json|ico|js)$

  - url: /(.*\.(html))$
    static_files: dist/\1
    upload: dist/.*\.(html)$

  - url: /(.*\.(css))$
    static_files: dist/\1
    upload: dist/.*\.(css)$

  - url: /.*
    script: auto
